### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/DotFiles#21]
1.GeeKlub Will Not Be Discarded

**Comment by HelloVass** [comment]
@wsdjeg Thanks，I hope so...

**Comment by wsdjeg** [comment]
@HelloVass is this [org](https://github.com/Geeklub) yours?

**Comment by HelloVass** [comment]
@wsdjeg no,it's belong to  [Jury Xiong's](https://github.com/portwatcher) friend.

**Comment by wsdjeg** [comment]
@HelloVass 我想大概了解下你们之前搞这个GKLUB的宗旨和目的是什么，而现在主要面向的对象是哪些，还是只是杭电的学生？如果你们目前有比较合适的交流平台，那么这个项目就显得没有什么意义了，当然qq群除外，那不是程序员该用的东西。

**Comment by HelloVass** [comment]
@wsdjeg 所有的东西应该都在[这里](https://coding.net/u/hellovass/p/GeeKlub/git)了,面向的对象是我们学校的。我的项目废弃是因为学弟说 coding 这种方式太 low，他要召集成员写一个官网。（然而，现在官网都还没出来）

**Comment by wsdjeg** [comment]
@HelloVass 为什么不让大家都上github来呢，你也看到了，在这里有很多比较前沿的项目可以学习，比起自己搞网站要好很多，而且github也支持项目主页，可以做一个静态的网站，配合一些社会化工具也能做评论用。

**Comment by HelloVass** [comment]
@wsdjeg 当然，大家都玩 github，也有 gklub 这个组织。然而用 github pages 搭建静态主页，还是老问题，nobody contributes the code！！！现在社团最大的问题，不是对外面的世界一无所知（相反，用的工具和协作工具都非常新潮），而是松散到快要不存在。。。

**Comment by wsdjeg** [comment]
@HelloVass 还是一个问题，我觉得社团不在乎人多人少，也许只有两三人也行，搞清楚大家的共同需求，大家才可以贡献代码，毕竟我想现在大多数人现在都有自己的工作，那么能否在空闲的时间来贡献代码，就依赖于他对于这个项目的需求程度。比如说我一直在跟进的几个项目，都是我需要的 
https://github.com/wsdjeg/syntastic
https://github.com/wsdjeg/vim-javacomplete2

**Comment by HelloVass** [comment]
@wsdjeg 是的，不在乎人多少，有同样想法，愿意贡献代码的即可。。。然而啊，目前来说，根本没有发起者。。。我也很无奈，看着社团的氛围一天天冷下去

**Comment by wsdjeg** [comment]
主要是没有共同的目标，如果大家有一致的目标，那么一切都会顺其自然了

**Comment by HelloVass** [comment]
@wsdjeg 是的，就像网上的一群网友，虽然从未见面，但是因为热爱某个项目，就会专心地投入，并且贡献代码

**Comment by wsdjeg** [comment]
你对vim熟悉么？有兴趣尝试下么？
https://github.com/wsdjeg/DotFiles

**Comment by HelloVass** [comment]
@wsdjeg 不熟悉，我之前主要从事 Android 开发，现在想尝试下 ruby，试试 rails...

**Comment by wsdjeg** [comment]
脚本语言非常适合用vim写，如果你是linux，可以尝试下neovim + deoplete.nvim，
