### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by iwannaflytomoon** [wsdjeg/DotFiles#25]
hi，wsdjeg
     最近一直在读你的这个DotFiles，你这个文件的布局方式和autoload下面的zvim挺有意思的，这是什么框架？另外请教下，nvim下面的插件比起vim的提升很大吗，值不值得从vim迁移到nvim

**Comment by wsdjeg** [comment]
Hi
 首先感谢关注我的这个配置文件集合.我的这个布局主要是将配置文件的各个部分分离,这便于Debug.zvim只是我临时写的一个小插件,目的在于提供一些公共的脚本工具.
 nvim的目的在于取出vim中臃肿的过时代码,https://github.com/neovim/neovim/wiki/Introduction  这个是它的介绍,我想这个比我说的更有用,我的配置文件是兼容vim和neovim的,两者打开以及使用起来基本上一样.我目前已经完全转移到nvim上,vim只是用来验证一些bug的.如果时间比较多,可以折腾下nvim,否则还是用稳定版的vim.

**Comment by iwannaflytomoon** [comment]
感谢回复，我在vim上用你的dotfiles没有问题，但是在osx下的nvim用就会报错。我搜了一下，可能是我nvim不支持python3的缘故，但是我的nvim就是brew install安装的啊，怎么让它支持python3呢

**Comment by wsdjeg** [comment]
你的nvim没有装py client吧，echo has("python3")是什么

**Comment by wsdjeg** [comment]
在我的dotfiles里面有一个stack/linux.md里面有如何让nvim支持py，需要pip和pip3

来自我的华为手机

-------- 原始邮件 --------
主题：Re: [DotFiles] hi (#25)
发件人：iwannaflytomoon
收件人：wsdjeg/DotFiles
抄送：Wang Shidong

感谢回复，我在vim上用你的dotfiles没有问题，但是在osx下的nvim用就会报错。我搜了一下，可能是我nvim不支持python3的缘故，但是我的nvim就是brew install安装的啊，怎么让它支持python3呢

---
