### ISSUE TITLE
How to support maven project

### ISSUE THREAD

**Issue by hacpai** [wsdjeg/DotFiles#30]
1. Download *.jar automatically
2. Jump jar source

**Comment by wsdjeg** [comment]
download jars is the work of maven,you can run 'mvn compile' in terminal.and maven do not support autodownload src.you need download your self.and add tags file

**Comment by wsdjeg** [comment]
and before answer your question,I need know what your os is,win or linux?

**Comment by hacpai** [comment]
@wsdjeg OS is Mac.

I have a question, how to add tags file?

**Comment by wsdjeg** [comment]
you need install ctags,and go to the path of jdk src. run 
```sh
cd java  #here only generate tags for java.*,if you need javax.do same thing in that dir
ctags -R
```
then add set tag+=path-to-tag-file  into your vimrc

**Comment by hacpai** [comment]
@wsdjeg I add  set tag+=path-to-tag-file into ~/.vim/vimrc, like this:

```vim
" Note: Skip initialization for vim-tiny or vim-small.
 if 1
    execute 'source' fnamemodify(expand('<sfile>'), ':h').'/config/main.        vim'
    set tag+=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/        Home/tags
endif
```

but it didn't work.

**Comment by hacpai** [comment]
@wsdjeg I unzip src.zip and run ```ctags -R```, then mv `tags` to `~/others/openjdksrc/java`

It works. Thank you for help.

**Comment by wsdjeg** [comment]
no problem,nice to hear that.so can be closed?

**Comment by hacpai** [comment]
@wsdjeg Ok, another issue can be closed too.
