### ISSUE TITLE
[question] Inconsistent nvim files

### ISSUE THREAD

**Issue by andersonba** [wsdjeg/DotFiles#31]
First, good job! 👍 

I think that you're using a different vim version from the current README file.
Some plugins don't work or have different keys binding or settings.
Like the installed ctrlp package, you don't talked about it in docs.

Are you refactoring now?

Thanks.

**Comment by wsdjeg** [comment]
yes the readme need to be updated.please wait.
ctrlp's hotkey is ctrl+p.it is default

**Comment by andersonba** [comment]
Nice, so, the nvim files are updated?
Why did you removed `C-[h, j, k, l]`hotkeys used to moving between splits? I saw it in README too, it's very cool.

**Comment by wsdjeg** [comment]
@andersonba I using `C-[up,down,left,right]`,even if in neovim's terminal buffer
`C - [j,k]` is hotkeys for vim-multiple-cursors
```vim
call s:add('terryma/vim-multiple-cursors')
    let g:multi_cursor_next_key='<C-j>'
    let g:multi_cursor_prev_key='<C-k>'
    let g:multi_cursor_skip_key='<C-x>'
    let g:multi_cursor_quit_key='<Esc>'
```
`ctrl + l` is a translate tool, translate english word under the cursor to chinese.
I do not use `ctrl + h` in normal mode

**Comment by wsdjeg** [comment]
@andersonba I have implement a new feature,you can list all the mappings in unite buffer with it's description. please see the picture in the readme of current repo.

**Comment by andersonba** [comment]
Awesome! 👍

**Comment by wsdjeg** [comment]
now you can use this func defind mappings;
`zvim#util#defindMap(type,key,value,desc,...)`
forexamp 
```vim
call zvim#util#defindMap('nnoremap', '[Window]', '<Nop>'   , 'Defind window prefix'   ,'normal [Window]')
call zvim#util#defindMap('nmap'    , 's' , '[Window]', 'Use s as window prefix' ,'normal s')

call zvim#util#defindMap('nnoremap <silent>', '<Tab>', ':wincmd w<CR>', 'Switch to another buffer','wincmd w')
call zvim#util#defindMap('nnoremap <silent>', '[Window]p', ':<C-u>vsplit<CR>:wincmd w<CR>',
            \'vsplit vertically,switch to next window','vsplit | wincmd w')
call zvim#util#defindMap('nnoremap <silent>', '[Window]v', ':<C-u>split<CR>', 'split window','split')

```
then you will see 
![2016-04-23-21 26 17](https://cloud.githubusercontent.com/assets/13142418/14761653/248f50ac-099a-11e6-9450-be3bd65227b0.png)

if you select anyone the map will be exxcuted
