### ISSUE TITLE
About support Spring Framework

### ISSUE THREAD

**Issue by hacpai** [wsdjeg/DotFiles#32]
I think DotFiles is very good, it make more friendly in writing Java code.

But in some company's project still use some framework, such as Spring Framework.

Is it support Spring Framework?

**Comment by wsdjeg** [comment]
How do you want this repo support Spring Framework,as I know ,most user use maven manage depedency,so you just need add the jars you need to pom.xml,and the vim can autoload pom.xml,and build classpath

**Comment by hacpai** [comment]
@wsdjeg What about Spring bean?  I wonder if a good way to Configure Spring and dependency injection.

**Comment by wsdjeg** [comment]
I can not understand ,can you show example repo?

**Comment by hacpai** [comment]
@wsdjeg Ok, this is a part of my project.

Look this,

```Java
public void setValue(String value) {
    this.value = Integer.parseInt(value);
}
```

I can jump to the spring bean property in example.xml easily.

```xml
<bean id="example" class="com.xxx.api.service.impl.example" autowire="byName" lazy-init="true">
        <property name="value" value="${tag.interest.register.random_tag_count}"/>
    </bean>
```

**Comment by wsdjeg** [comment]
Need more investigation about this...

**Comment by wsdjeg** [comment]
@hacpai It is hard to implement. Do you have any idea?
