### ISSUE TITLE
请问支持 mac os 吗?

### ISSUE THREAD

**Issue by manielng** [wsdjeg/DotFiles#35]
# Problems summary

## Environment Information
 * OS:
 * vim version:
 * neovim version:

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by wsdjeg** [comment]
I am not sure,but you can have a try,I think it should works same as linux

**Comment by oero** [comment]
@wsdjeg 

环境:ubuntu 14.04
在neovim怎么用?

**Comment by wsdjeg** [comment]
@oero clone this repo
run
`./install.sh nvim`

**Comment by wsdjeg** [comment]
14.04的gnome-terminal 对真色支持有问题,请按照我的linux.md里面的内容,安装新版的终端,在stack文件夹内

**Comment by oero** [comment]
运行 ./install.sh nvim  命令后

出现
Skipping /home/oero/.config/nvim

**Comment by wsdjeg** [comment]
说明你有这个文件夹了,这应该是你原来的配置,你可以删了,或者备份

**Comment by oero** [comment]
恩,我之前在这个目录下有nvim的配置

现在输入nvim  
它在下载一些没有安装的插件
这样就行了?

**Comment by wsdjeg** [comment]
对,全陈 自动安装

**Comment by oero** [comment]
目前用的是zsh

![alt tag] (https://github.com/oero/oero.github.io/blob/master/Screenshot%20from%202016-04-23%2022:27:21.png)
