### ISSUE TITLE
Error occurred while loading vimproc

### ISSUE THREAD

**Issue by wulliam** [wsdjeg/DotFiles#38]
# Problems summary
Error occurred while loading vimproc

## Environment Information
 * OS: OSX10.10.5
 * vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 25 2016 00:02:44)
MacOS X (unix) version
Included patches: 1-944
Compiled by Homebrew
 * neovim version:
NVIM 0.1.3
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/build/config -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/src -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/build/src/nvim/auto -I/tmp/neovim20160424-1724-1rzjium/neovim-0.1.3/build/include

## The reproduce ways from Vim starting (Required!)
After fresh install, I want to use VimFile and thet the error

## Upload the log messages by `:redir` and `:message`
[vimproc] vimproc's DLL: "/Users/winton.wu/.cache/vimfiles/.dein/lib/vimproc_mac
.so" is not found.  Please read :help vimproc and make it.
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
Error occurred while loading vimproc.
Please install vimproc Ver.6.0 or above.

**Comment by wsdjeg** [comment]
there are two errors 

- vimproc need to be compiled
[Shougo/vimproc] beed to be compile after install,but by default,it should be auto build by dein( vim plugin manager)
see https://github.com/wsdjeg/DotFiles/blob/master/config/nvim/config/plugins.vim#L142
how about `:call dein#reinstall(['vimproc.vim'])`

- also you need install ctags for Tagbar.

**Comment by wulliam** [comment]
I manually build vimproc in ".cache/vimfiles/repos/github.com/Shougo/vimproc.vim" folder, and make a symlink like "ln -s ~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim/lib .cache/vimfiles/.dein/lib", then "FIleFiler" works well. (please note, the symlink is required, otherwise the vimproc_mac
.so still can not found)

**Comment by wsdjeg** [comment]
I do not know why,it works well for me.I think maybe you need `call dein#recache_runtimepath()`

**Comment by Shougo** [comment]
@wulliam You must build vimproc by dein.

```vim
call dein#add('Shougo/vimproc.vim', {'build': 'make'})
```

**Comment by wsdjeg** [comment]
![2016-05-02-16 11 06](https://cloud.githubusercontent.com/assets/13142418/14949932/9e2dc4ec-1080-11e6-8c35-f05dfae4a085.png)
![2016-05-02-16 12 18](https://cloud.githubusercontent.com/assets/13142418/14949956/c35a9394-1080-11e6-8f46-5118b7954db9.png)

**Comment by gbcreation** [comment]
Just for information, what Unite source do you use in your second screeshot ?

**Comment by wsdjeg** [comment]
@gbcreation I do not use any unite source,it is unite menu.you can see it in plugins.vim in my dotfiles
