### ISSUE TITLE
只能在root用户下才能使用，如何才能配置普通用户才能使用

### ISSUE THREAD

**Issue by linweijun** [wsdjeg/DotFiles#50]
OS：Fedora24。
如题。

**Comment by wsdjeg** [comment]
为什么是只能在root用户下使用, 其实 不用搞太复杂的设置, 只需要将我这个内的`config/nvim/` 文件夹复制成`~/.vim`,并且删掉你自己原来的`~/.vimrc`就可以了.

**Comment by wsdjeg** [comment]
如果你需要使用安装脚本, 请确认你的终端没有使用root账户, 然后执行`./install.sh vim`

**Comment by wsdjeg** [comment]
no response
