### ISSUE TITLE
Window terminal

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/DotFiles#56]
I want to use terminal in window, but I can not find which one I should use, the I just find VimShell, I hope I find it early,

http://www.myhack58.com/Article/48/65/2014/47821.htm
https://github.com/bmatzelle/gow

**Comment by tracyone** [comment]
try http://msys2.github.io/

**Comment by wsdjeg** [comment]
@tracyone thanks , I just reinstall archlinux.
