### ISSUE TITLE
screenshorts

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/DotFiles#67]
![2017-11-19-22 01 16](https://user-images.githubusercontent.com/13142418/32991414-145bcade-cd76-11e7-81d4-9cb2107ab421.png)

**Comment by wsdjeg** [comment]
![2017-11-19-22 39 29](https://user-images.githubusercontent.com/13142418/32991690-51397e6a-cd7b-11e7-8b98-b5db89798a19.png)

**Comment by wsdjeg** [comment]
![2017-11-22-23-07-02](https://user-images.githubusercontent.com/13142418/33134450-608cacfc-cf65-11e7-856f-5a870d2d6787.gif)

![firfox](https://user-images.githubusercontent.com/13142418/33130755-fd1d2508-cf59-11e7-83ed-bfbfd332b1be.gif)

**Comment by wsdjeg** [comment]
![2017-11-22-23 19 50](https://user-images.githubusercontent.com/13142418/33135117-76f45b9e-cfdc-11e7-869f-cee22bd37c37.png)
![2017-11-22-23 19 43](https://user-images.githubusercontent.com/13142418/33135119-7734a032-cfdc-11e7-8412-ff8f59747da1.png)

**Comment by lroolle** [comment]
Cool

**Comment by wsdjeg** [comment]
![2017-12-01-23-43-40](https://user-images.githubusercontent.com/13142418/33490542-24af3960-d67d-11e7-990a-a78e825d80ca.gif)

**Comment by wsdjeg** [comment]
![2018-01-05-21 58 11](https://user-images.githubusercontent.com/13142418/34612367-18fdf2d6-f1ef-11e7-885e-5e82613c1444.png)

**Comment by wsdjeg** [comment]
![2018-01-19-20-59-29-fix](https://user-images.githubusercontent.com/13142418/35153690-253d8f8a-fced-11e7-85f7-3790515a318d.gif)

**Comment by wsdjeg** [comment]
![2018-01-23-19-44-03](https://user-images.githubusercontent.com/13142418/35274503-e5c1658a-0001-11e8-8719-a6e88c55d9fa.gif)
![2018-01-23-19-44-42](https://user-images.githubusercontent.com/13142418/35274522-f4788b6c-0001-11e8-91f2-2e45e18fd343.gif)
![2018-01-23-19-45-21](https://user-images.githubusercontent.com/13142418/35274523-f4c5e934-0001-11e8-97a5-a9f504c8b1f0.gif)

**Comment by wsdjeg** [comment]
![searching_project](https://user-images.githubusercontent.com/13142418/35278709-7856ed62-0010-11e8-8b1e-e6cc6374b0dc.gif)

**Comment by wsdjeg** [comment]
![searching-current-file](https://user-images.githubusercontent.com/13142418/35278847-e0032796-0010-11e8-911b-2ee8fd81aed2.gif)

**Comment by wsdjeg** [comment]
![searching-loaded-buffer](https://user-images.githubusercontent.com/13142418/35278996-518b8a34-0011-11e8-9a7a-613668398ee2.gif)

**Comment by wsdjeg** [comment]
![pluginmanager_fixed](https://user-images.githubusercontent.com/13142418/35566722-ff1824ac-0587-11e8-9e1f-8c9974872b36.gif)

**Comment by GitHuberrr** [comment]
太棒了，兄弟，很厉害

**Comment by wsdjeg** [comment]
fuck 知乎

![2018-03-23-23-54-33](https://user-images.githubusercontent.com/13142418/37839922-bce94234-2e89-11e8-9758-5d360faab6ec.gif)

**Comment by wsdjeg** [comment]
![pg11](https://user-images.githubusercontent.com/13142418/63637793-9a332700-c6b3-11e9-9d54-c18e4ee81878.jpg)
